//data store for airport codes

let airportCodeData = {
    "Aleknagik": "5A8",
    "Andalusia": "79J",
    "Allentown": "ABE",
    "Abilene": "ABI",
    "Albuquerque": "ABQ",
    "Aberdeen": "ABR",
    "Albany": "ABY",
    "Nantucket": "ACK",
    "Waco": "ACT",
    "Arcata": "ACV",
    "Atlantic City": "ACY",
    "Camp Springs": "ADW",
    "Alexandria": "AEX",
    "Fort Worth": "AFW",
    "Pittsburgh": "AGC",
    "Augusta": "AGS",
    "Athens": "AHN",
    "Akron": "AKR",
    "Albany": "ALB",
    "Alice": "ALI",
    "Alamogordo": "ALM",
    "St Louis": "ALN",
    "Waterloo": "ALO",
    "Alamosa": "ALS",
    "Walla Walla": "ALW",
    "Amarillo": "AMA",
    "Anniston": "ANB",
    "Anderson": "AND",
    "Altoona": "AOO",
    "Denver": "APA",
    "Naples": "APF",
    "Aberdeen": "APG",
    "Alpena": "APN",
    "New Iberia": "ARA",
    "Watertown": "ART",
    "Aspen": "ASE",
    "Astoria": "AST",
    "Atlanta": "ATL",
    "Watertown": "ATY",
    "Augusta": "AUG",
    "Austin": "AUS",
    "Wausau": "AUW",
    "Asheville": "AVL",
    "Scranton": "AVP",
    "Alexandria": "AXN",
    "Kalamazoo": "AZO",
    "Marysville": "BAB",
    "Bossier City": "BAD",
    "Westfield": "BAF",
    "Columbus": "BAK",
    "Brady": "BBD",
    "Bryce Canyon": "BCE",
    "Baudette": "BDE",
    "Hartford": "BDL",
    "Bridgeport": "BDR",
    "Bedford": "BED",
    "Bradford": "BFD",
    "Scottsbluff": "BFF",
    "Seattle": "BFI",
    "Bakersfield": "BFL",
    "Mobile": "BFM",
    "Binghamton": "BGM",
    "Bangor": "BGR",
    "Bar Harbor": "BHB",
    "Birmingham": "BHM",
    "Fort Bliss": "BIF",
    "Bishop": "BIH",
    "Billings": "BIL",
    "Bismarck": "BIS",
    "Biloxi": "BIX",
    "Denver": "BJC",
    "Bemidji": "BJI",
    "Baker City": "BKE",
    "Aurora": "BKF",
    "Cleveland": "BKL",
    "Beckley": "BKW",
    "Bluefield": "BLF",
    "Blythe": "BLH",
    "Bellingham": "BLI",
    "Belleville": "BLV",
    "Bloomington": "BMG",
    "Bloomington": "BMI",
    "Nashville": "BNA",
    "Burns": "BNO",
    "Boise": "BOI",
    "Boston": "BOS",
    "Big Piney": "BPI",
    "Mountain Home": "BPK",
    "Port Arthur": "BPT",
    "Brunswick": "BQK",
    "Brainerd": "BRD",
    "Burlington": "BRL",
    "Brownsville": "BRO",
    "Battle Creek": "BTL",
    "Butte": "BTM",
    "Baton Rouge": "BTR",
    "Burlington": "BTV",
    "Buffalo": "BUF",
    "Burbank": "BUR",
    "Beaver Falls": "BVI",
    "Beverly": "BVY",
    "Bowling Green": "BWG",
    "Baltimore": "BWI",
    "Blytheville": "BYH",
    "Burley": "BYI",
    "Fort Irwin": "BYS",
    "Bozeman": "BZN",
    "Columbia": "CAE",
    "Akron": "CAK",
    "Caribou": "CAR",
    "Columbus": "CBM",
    "Charles City": "CCY",
    "Cedar City": "CDC",
    "Chadron": "CDR",
    "Childress": "CDS",
    "Crescent City": "CEC",
    "Chicopee": "CEF",
    "Crestview": "CEW",
    "Cleveland": "CGF",
    "Cape Girardeau": "CGI",
    "Chattanooga": "CHA",
    "Charlottesville": "CHO",
    "Charleston": "CHS",
    "Cedar Rapids": "CID",
    "Sault Ste Marie": "CIU",
    "Clarksburg": "CKB",
    "Cleveland": "CLE",
    "College Station": "CLL",
    "Port Angeles": "CLM",
    "Charlotte": "CLT",
    "Columbus": "CMH",
    "Champaign": "CMI",
    "Hancock": "CMX",
    "Carlsbad": "CNM",
    "Chanute": "CNU",
    "Cody": "COD",
    "Coeur d'Alene": "COE",
    "Cocoa Beach": "COF",
    "Concord": "CON",
    "Colorado Springs": "COS",
    "Columbia": "COU",
    "Casper": "CPR",
    "North Myrtle Beach": "CRE",
    "Jacksonville": "CRG",
    "Corpus Christi": "CRP",
    "Carlsbad": "CRQ",
    "Charleston": "CRW",
    "Columbus": "CSG",
    "Crossville": "CSV",
    "Cut Bank": "CTB",
    "Columbia": "CUB",
    "Cincinnati": "CVG",
    "Corvallis": "CVO",
    "Clovis": "CVS",
    "Mosinee": "CWA",
    "Houston": "CXO",
    "Cheyenne": "CYS",
    "Fort Belvoir": "DAA",
    "Daytona Beach": "DAB",
    "Daggett": "DAG",
    "Dallas": "DAL",
    "Danville": "DAN",
    "Dayton": "DAY",
    "Dubuque": "DBQ",
    "Washington": "DCA",
    "Dodge City": "DDC",
    "Decatur": "DEC",
    "Denver": "DEN",
    "Detroit": "DET",
    "Dallas-Fort Worth": "DFW",
    "Dothan": "DHN",
    "Dalhart": "DHT",
    "Dickinson": "DIK",
    "Del Rio": "DLF",
    "Duluth": "DLH",
    "The Dalles": "DLS",
    "Tucson": "DMA",
    "Deming": "DMN",
    "Augusta": "DNL",
    "Dover": "DOV",
    "Chicago": "DPA",
    "Mercury": "NV65",
    "De Ridder": "DRI",
    "Del Rio": "DRT",
    "Des Moines": "DSM",
    "Detroit": "DTW",
    "Douglas Bisbee": "DUG",
    "Dubois": "DUJ",
    "Abilene": "DYS",
    "Wenatchee": "EAT",
    "Eau Claire": "EAU",
    "Elizabeth City": "ECG",
    "Panama City Beach": "ECP",
    "Edwards": "EDW",
    "Needles": "EED",
    "Keene": "EEN",
    "Alabaster": "EET",
    "Houston": "EFD",
    "Eagle": "EGE",
    "Crestview": "EGI",
    "Eureka": "EKA",
    "Elkins": "EKN",
    "Elko": "EKO",
    "El Dorado": "ELD",
    "Elmira": "ELM",
    "Ely": "ELO",
    "El Paso": "ELP",
    "Ely": "ELY",
    "Enid": "END",
    "Wendover": "ENV",
    "Kenosha": "ENW",
    "Erie": "ERI",
    "Alexandria": "ESF",
    "Eugene": "EUG",
    "Evansville": "EVV",
    "Evanston": "EVW",
    "New Bedford": "EWB",
    "New Bern": "EWN",
    "Newark": "EWR",
    "Key West": "EYW",
    "Fort Eustis": "FAF",
    "Fargo": "FAR",
    "Fresno": "FAT",
    "Fayetteville": "FAY",
    "Fort Bragg": "FBG",
    "Fort Carson": "FCS",
    "Findlay": "FDY",
    "Dayton": "FFO",
    "Fort Huachuca Sierra Vista": "FHU",
    "Franklin": "FKL",
    "Flagstaff": "FLG",
    "Fort Lauderdale": "FLL",
    "Florence": "FLO",
    "Fort Meade": "FME",
    "Farmington": "FMN",
    "Fort Myers": "FMY",
    "Flint": "FNT",
    "Fort Dodge": "FOD",
    "Topeka": "FOE",
    "Fort Pierce": "FPR",
    "Farmingdale": "FRG",
    "Fort Riley": "FRI",
    "Sioux Falls": "FSD",
    "Fort Sill": "FSI",
    "Fort Smith": "FSM",
    "Fort Stockton": "FST",
    "Fort Knox": "FTK",
    "Fort Worth": "FTW",
    "Atlanta": "FTY",
    "Fort Wayne": "FWA",
    "Fort Lauderdale": "FXE",
    "Fayetteville": "FYV",
    "Gillette": "GCC",
    "Garden City": "GCK",
    "Grand Canyon": "GCN",
    "Glendive": "GDV",
    "Spokane": "GEG",
    "Grand Forks": "GFK",
    "Glens Falls": "GFL",
    "Longview": "GGG",
    "Glasgow": "GGW",
    "Grand Junction": "GJT",
    "Goodland": "GLD",
    "Greenville": "GLH",
    "Galveston": "GLS",
    "Greenville": "GMU",
    "Gainesville": "GNV",
    "Groton": "GON",
    "Kalispell": "GPI",
    "Gulfport": "GPT",
    "Green Bay": "GRB",
    "Fort Lewis": "GRF",
    "Grand Island": "GRI",
    "Fort Hood": "GRK",
    "Grand Rapids": "GRR",
    "Goldsboro": "GSB",
    "Greensboro": "GSO",
    "Greenville": "GSP",
    "Fort Drum": "GTB",
    "Great Falls": "GTF",
    "Starkville": "GTR",
    "Gallup": "GUP",
    "Peru": "GUS",
    "Guymon": "GUY",
    "Greenwood": "GWO",
    "Gary": "GYY",
    "Hattiesburg": "HBG",
    "Hobart": "HBR",
    "Hartford": "HFD",
    "Hagerstown": "HGR",
    "Hawthorne": "HHR",
    "Hibbing": "HIB",
    "Ogden": "HIF",
    "Portland": "HIO",
    "Hickory": "HKY",
    "Wheeling": "HLG",
    "Helena": "HLN",
    "Fort Hood": "HLR",
    "Alamogordo": "HMN",
    "Hobbs": "HOB",
    "Huron": "HON",
    "Fort Campbell": "HOP",
    "Hot Springs": "HOT",
    "Houston": "HOU",
    "White Plains": "HPN",
    "Hoquiam": "HQM",
    "Harlingen": "HRL",
    "Harrison": "HRO",
    "Mary Esther": "HRT",
    "Homestead": "HST",
    "Huntsville": "HSV",
    "Huntington": "HTS",
    "Redstone Arsnl Huntsville": "HUA",
    "Terre Haute": "HUF",
    "Houlton": "HUL",
    "Hutchinson": "HUT",
    "New Haven": "HVN",
    "Havre": "HVR",
    "Hyannis": "HYA",
    "San Marcos": "HYI",
    "Hayward": "HYR",
    "Hays": "HYS",
    "Wichita": "IAB",
    "Washington": "IAD",
    "Niagara Falls": "IAG",
    "Houston": "IAH",
    "Wichita": "ICT",
    "Idaho Falls": "IDA",
    "Kankakee": "IKK",
    "Wilmington": "ILG",
    "Wilmington": "ILM",
    "Wilmington": "ILN",
    "Indianapolis": "IND",
    "Wink": "INK",
    "International Falls": "INL",
    "Winston Salem": "INT",
    "Winslow": "INW",
    "Imperial": "IPL",
    "Williamsport": "IPT",
    "Kirksville": "IRK",
    "Orlando": "ISM",
    "Williston": "ISN",
    "Kinston": "ISO",
    "Islip": "ISP",
    "Ithaca": "ITH",
    "Phoenix": "IWA",
    "Jackson": "JAC",
    "Jackson": "JAN",
    "Jacksonville": "JAX",
    "Jonesboro": "JBR",
    "Junction": "JCT",
    "New York": "JFK",
    "Jamestown": "JHW",
    "Jackson": "JKL",
    "Joplin": "JLN",
    "Jamestown": "JMS",
    "Johnstown": "JST",
    "Jackson": "JXN",
    "Kelso": "KLS",
    "Lafayette": "LAF",
    "Lakeland": "LAL",
    "Lansing": "LAN",
    "Laramie": "LAR",
    "Las Vegas": "LAS",
    "Lawton": "LAW",
    "Los Angeles": "LAX",
    "Lubbock": "LBB",
    "Latrobe": "LBE",
    "North Platte": "LBF",
    "Liberal": "LBL",
    "Lumberton": "LBT",
    "Angleton": "LBX",
    "Lake Charles": "LCH",
    "Columbus": "LCK",
    "Lebanon": "LEB",
    "Leesburg": "LEE",
    "Lexington": "LEX",
    "Hampton": "LFI",
    "Lufkin": "LFK",
    "Lafayette": "LFT",
    "New York": "LGA",
    "Long Beach": "LGB",
    "Logan": "LGU",
    "Little Rock": "LIT",
    "Monticello": "LLQ",
    "Klamath Falls": "LMT",
    "Lander": "LND",
    "Lincoln": "LNK",
    "Lancaster": "LNS",
    "Lovelock": "LOL",
    "Louisville": "LOU",
    "London": "LOZ",
    "Laredo": "LRD",
    "Jacksonville": "LRF",
    "Las Cruces": "LRU",
    "La Crosse": "LSE",
    "Fort Benning": "LSF",
    "Las Vegas": "LSV",
    "Altus": "LTS",
    "Glendale": "LUF",
    "Cincinnati": "LUK",
    "Livingston": "LVM",
    "Las Vegas": "LVS",
    "Lewisburg": "LWB",
    "Lawrence": "LWM",
    "Lewiston": "LWS",
    "Lewistown": "LWT",
    "Lynchburg": "LYH",
    "Midland": "MAF",
    "Mobridge": "MBG",
    "Saginaw": "MBS",
    "Mc Comb": "MCB",
    "Sacramento": "MCC",
    "Merced": "MCE",
    "Tampa": "MCF",
    "Kansas City": "MCI",
    "Mc Cook": "MCK",
    "Macon": "MCN",
    "Orlando": "MCO",
    "Mason City": "MCW",
    "Carbondale": "MDH",
    "Harrisburg": "MDT",
    "Chicago": "MDW",
    "Meridian": "MEI",
    "Memphis": "MEM",
    "Merced": "MER",
    "Mansfield": "MFD",
    "Mc Allen": "MFE",
    "Medford": "MFR",
    "Marietta": "MGE",
    "Montgomery": "MGM",
    "Morgantown": "MGW",
    "Manhattan": "MHK",
    "Sacramento": "MHR",
    "Manchester": "MHT",
    "Miami": "MIA",
    "Minot": "MIB",
    "Muncie": "MIE",
    "Millville": "MIV",
    "Kansas City": "MKC",
    "Milwaukee": "MKE",
    "Jackson": "MKL",
    "Melbourne": "MLB",
    "Mc Alester": "MLC",
    "Moline": "MLI",
    "Miles City": "MLS",
    "Monroe": "MLU",
    "Eastover": "MMT",
    "Morristown": "MMU",
    "Mc Minnville": "MMV",
    "Mobile": "MOB",
    "Modesto": "MOD",
    "Minot": "MOT",
    "Montpelier": "MPV",
    "Smyrna": "MQY",
    "Martinsburg": "MRB",
    "Monterey": "MRY",
    "Muscle Shoals": "MSL",
    "Madison": "MSN",
    "Missoula": "MSO",
    "Minneapolis": "MSP",
    "Massena": "MSS",
    "New Orleans": "MSY",
    "Mount Clemens": "MTC",
    "Marathon": "MTH",
    "Montrose": "MTJ",
    "Baltimore": "MTN",
    "Fort Indiantown Gap": "MUI",
    "Mountain Home": "MUO",
    "Moses Lake": "MWH",
    "Montgomery": "MXF",
    "McCall": "MYL",
    "Myrtle Beach": "MYR",
    "Marysville": "MYV",
    "Beaufort": "NBC",
    "New Orleans": "NBG",
    "Jacksonville": "NCA",
    "Milton": "NDZ",
    "Lakehurst": "NEL",
    "New Orleans": "NEW",
    "Oceanside": "NFG",
    "Fallon": "NFL",
    "Fort Worth": "NFW",
    "Corpus Christi": "NGP",
    "Norfolk": "NGU",
    "Patuxent River": "NHK",
    "Brunswick": "BXM",
    "China Lake": "NID",
    "Jacksonville": "NIP",
    "El Centro": "NJK",
    "Cherry Point": "NKT",
    "San Diego": "NKX",
    "Lemoore": "NLC",
    "Meridian": "NMM",
    "Pensacola": "NPA",
    "Millington": "NQA",
    "Kingsville": "NQI",
    "Key West": "NQX",
    "Mayport": "NRB",
    "Milton": "NSE",
    "Point Mugu": "NTD",
    "Virginia Beach": "NTU",
    "Mountain View": "NUQ",
    "Oak Harbor": "NUW",
    "Twentynine Palms": "NXP",
    "Quantico": "NYG",
    "Yuma": "NYL",
    "San Diego": "NZY",
    "Jacksonville": "OAJ",
    "Oakland": "OAK",
    "Omaha": "OFF",
    "Norfolk": "OFK",
    "Orangeburg": "OGB",
    "Ogden": "OGD",
    "Oklahoma City": "OKC",
    "Wolf Point": "OLF",
    "Olympia": "OLM",
    "Nogales": "OLS",
    "Columbus": "OLU",
    "Omaha": "OMA",
    "Newport": "ONP",
    "Ontario": "ONT",
    "Miami": "OPF",
    "North Kingstown": "OQU",
    "Chicago": "ORD",
    "Norfolk": "ORF",
    "Worcester": "ORH",
    "Oshkosh": "OSH",
    "Columbus": "OSU",
    "North Bend": "OTH",
    "Ottumwa": "OTM",
    "Owensboro": "OWB",
    "Norwood": "OWD",
    "Oxnard": "OXR",
    "Ozark": "OZR",
    "Everett": "PAE",
    "Paducah": "PAH",
    "Panama City": "PAM",
    "Pine Bluff": "PBF",
    "Plattsburgh": "PBG",
    "West Palm Beach": "PBI",
    "Atlanta": "PDK",
    "Pendleton": "PDT",
    "Portland": "PDX",
    "Page": "PGA",
    "Greenville": "PGV",
    "Newport News": "PHF",
    "Philadelphia": "PHL",
    "Phoenix": "PHX",
    "Peoria": "PIA",
    "Hattiesburg": "PIB",
    "St Petersburg": "PIE",
    "Pocatello": "PIH",
    "Pierre": "PIR",
    "Pittsburgh": "PIT",
    "Parkersburg": "PKB",
    "Pellston": "PLN",
    "Palmdale": "PMD",
    "Pinedale": "PNA",
    "Ponca City": "PNC",
    "Philadelphia": "PNE",
    "Pensacola": "PNS",
    "Fayetteville": "POB",
    "Fort Polk": "POE",
    "Poughkeepsie": "POU",
    "Presque Isle": "PQI",
    "Paso Robles": "PRB",
    "Prescott": "PRC",
    "Paris": "PRX",
    "Pasco": "PSC",
    "Portsmouth": "PSM",
    "Palm Springs": "PSP",
    "Pontiac": "PTK",
    "Pullman/Moscow": "PUW",
    "Providence": "PVD",
    "Provo": "PVU",
    "Chicago": "PWK",
    "Portland": "PWM",
    "Bremerton": "PWT",
    "Riverside": "RAL",
    "Rapid City": "RAP",
    "Red Bluff": "RBL",
    "Rapid City": "RCA",
    "Redding": "RDD",
    "Reading": "RDG",
    "Redmond": "RDM",
    "Grand Forks": "RDR",
    "Raleigh": "RDU",
    "Chicago": "RFD",
    "Rhinelander": "RHI",
    "Richmond": "RIC",
    "Rifle": "RIL",
    "Riverside": "RIV",
    "Riverton": "RIW",
    "Rock Springs": "RKS",
    "Rome": "RME",
    "Rome": "RMG",
    "Universal City": "RND",
    "New Richmond": "RNH",
    "Reno": "RNO",
    "Roanoke": "ROA",
    "Rochester": "ROC",
    "Roswell": "ROW",
    "Russell": "RSL",
    "Rochester": "RST",
    "Fort Myers": "RSW",
    "Rutland": "RUT",
    "Tulsa": "RVS",
    "Redwood Falls": "RWF",
    "Rocky Mount": "RWI",
    "Rawlins": "RWL",
    "Atlanta": "RYY",
    "Sacramento": "SAC",
    "Santa Fe": "SAF",
    "San Diego": "SAN",
    "San Antonio": "SAT",
    "Savannah": "SAV",
    "Marquette": "SAW",
    "Santa Barbara": "SBA",
    "San Bernardino": "SBD",
    "South Bend": "SBN",
    "San Luis Obispo": "SBP",
    "Salisbury": "SBY",
    "Schenectady": "SCH",
    "Stockton": "SCK",
    "Louisville": "SDF",
    "San Diego": "SDM",
    "Sidney": "SDY",
    "Seattle": "SEA",
    "Orlando": "SFB",
    "Spokane": "SFF",
    "San Francisco": "SFO",
    "Springfield": "SGF",
    "Springfield": "SGH",
    "St Augustine": "SGJ",
    "Houston": "SGR",
    "St George": "SGU",
    "Sheridan": "SHR",
    "Shreveport": "SHV",
    "San Jose": "SJC",
    "San Angelo": "SJT",
    "Spokane": "SKA",
    "San Antonio": "SKF",
    "Salt Lake City": "SLC",
    "Salem": "SLE",
    "Los Alamitos": "SLI",
    "Saranac Lake": "SLK",
    "Salina": "SLN",
    "Somerset": "SME",
    "Sacramento": "SMF",
    "Salmon": "SMN",
    "Santa Maria": "SMX",
    "Santa Ana": "SNA",
    "Salinas": "SNS",
    "Sidney": "SNY",
    "Sonora": "SOA",
    "Springfield": "SPI",
    "Wichita Falls": "SPS",
    "Sarasota": "SRQ",
    "Ruidoso": "SRR",
    "Sumter": "SSC",
    "San Antonio": "SSF",
    "Brunswick": "SSI",
    "St Cloud": "STC",
    "St Joseph": "STJ",
    "St Louis": "STL",
    "St Paul": "STP",
    "Santa Rosa": "STS",
    "Hailey": "SUN",
    "St Louis": "SUS",
    "Fairfield": "SUU",
    "Sioux City": "SUX",
    "Benton": "SUZ",
    "Savannah": "SVN",
    "Newburgh": "SWF",
    "Stillwater": "SWO",
    "Syracuse": "SYR",
    "Knob Noster": "SZL",
    "Fort Leonard Wood": "TBN",
    "Tucumcari": "TCC",
    "Tuscaloosa": "TCL",
    "Tacoma": "TCM",
    "Truth Or Consequences": "TCS",
    "Teterboro": "TEB",
    "Oklahoma City": "TIK",
    "Tacoma": "TIW",
    "Titusville": "TIX",
    "Tallahassee": "TLH",
    "Miami": "TMB",
    "Troy": "TOI",
    "Toledo": "TOL",
    "Topeka": "TOP",
    "Tampa": "TPA",
    "Tonopah": "TPH",
    "Temple": "TPL",
    "Kingsport": "TRI",
    "Truckee": "TRK",
    "Palm Springs": "TRM",
    "Portland": "TTD",
    "Trenton": "TTN",
    "Titusville": "TTS",
    "Tulsa": "TUL",
    "Tupelo": "TUP",
    "Tucson": "TUS",
    "Traverse City": "TVC",
    "South Lake Tahoe": "TVL",
    "Twin Falls": "TWF",
    "Texarkana": "TXK",
    "Tyler": "TYR",
    "Knoxville": "TYS",
    "Aurora": "UAO",
    "Quincy": "UIN",
    "Ukiah": "UKI",
    "State College": "UNV",
    "Oxford": "UOX",
    "Huntsville": "UTS",
    "Valdosta": "VAD",
    "Lompoc": "VBG",
    "Victoria": "VCT",
    "Vernal": "VEL",
    "Las Vegas": "VGT",
    "Valdosta": "VLD",
    "Van Nuys": "VNY",
    "Camp Douglas": "VOK",
    "Valparaiso": "VPS",
    "Valparaiso": "VPZ",
    "Vero Beach": "VRB",
    "Valentine": "VTN",
    "Clarksville": "W63",
    "Lancaster": "WJF",
    "Winnemucca": "WMC",
    "Warner Robins": "WRB",
    "Wrightstown": "WRI",
    "Worland": "WRL",
    "Wildwood": "WWD",
    "Woodward": "WWR",
    "West Yellowstone": "WYS",
    "Cocoa Beach": "XMR",
    "Fayetteville": "XNA",
    "Detroit": "YIP",
    "Yakima": "YKM",
    "Yankton": "YKN",
    "Youngstown/Warren": "YNG",
    "Zanesville": "ZZV",
    "Palmer": "PAQ",
    "Barter Island Lrrs": "BTI",
    "Bethel": "BET",
    "Delta Junction Ft Greely": "BIG",
    "Buckland": "BVK",
    "Wiley Post": "BRW",
    "Bettles": "BTT",
    "Birchwood": "BCV",
    "Cold Bay": "CDB",
    "Clear": "Z84",
    "Scammon Bay": "SCM",
    "Cordova": "CDV",
    "Cape Romanzof": "CZF",
    "Deering": "DEE",
    "Adak Island": "ADK",
    "Dillingham": "DLG",
    "Marshall": "MDM",
    "Kodiak": "ADQ",
    "Unalaska": "DUT",
    "Anchorage": "EDF",
    "Cape Newenham": "EHM",
    "Fairbanks": "EIL",
    "Emmonak": "ENM",
    "Kenai": "ENA",
    "Fairbanks": "FAI",
    "Fairbanks": "FBK",
    "Kake": "AFE",
    "Ambler": "AFM",
    "Galena": "GAL",
    "Gulkana": "GKN",
    "Gambell": "GAM",
    "Gustavus": "GST",
    "Holy Cross": "HCA",
    "Huslia": "HLA",
    "Haines": "HNS",
    "Homer": "HOM",
    "Hooper Bay": "HPB",
    "Egegik": "EII",
    "Kiana": "IAN",
    "Iliamna": "ILI",
    "Utopia Creek": "UTO",
    "Juneau": "JNU",
    "King Salmon": "AKN",
    "Anaktuvuk Pass": "AKP",
    "Ketchikan": "KTN",
    "Klawock": "AKW",
    "Cape Lisburne": "LUR",
    "McGrath": "MCG",
    "Anchorage": "MRI",
    "Mekoryuk": "MYU",
    "Anchorage": "ANC",
    "Aniak": "ANI",
    "Nenana": "ENN",
    "Annette": "ANN",
    "Anvik": "ANV",
    "Nome": "OME",
    "Northway": "ORT",
    "Kotzebue": "OTZ",
    "St George": "PBV",
    "Port Clarence": "KPC",
    "Petersburg": "PSG",
    "Port Heiden": "PTH",
    "Platinum": "PTU",
    "Nuiqsut": "AQT",
    "Arctic Village": "ARC",
    "Ruby": "RBY",
    "Savoonga": "SVA",
    "Deadhorse": "SCC",
    "Sand Point": "SDP",
    "Shishmaref": "SHH",
    "Sitka": "SIT",
    "Selawik": "WLK",
    "St Mary's": "KSM",
    "St Paul Island": "SNP",
    "Sparrevohn": "SVW",
    "Soldotna": "SXQ",
    "Shemya": "SYA",
    "Togiak Village": "TOG",
    "Talkeetna": "TKA",
    "Takotna": "TLJ",
    "Atqasuk": "ATK",
    "Valdez": "VDZ",
    "Kivalina": "KVL",
    "Seward": "SWD",
    "Wrangell": "WRG",
    "Wainwright": "AWI",
    "Noatak": "WTK",
    "Wasilla": "IYS",
    "Yakutat": "YAK",
    "Fort Yukon": "FYU",
    "Kekaha": "BKH",
    "Mokuleia": "HDH",
    "Wahiawa": "HHI",
    "Hana": "HNM",
    "Lahaina": "JHM",
    "Kapolei": "JRF",
    "Kailua/Kona": "KOA",
    "Lihue": "LIH",
    "Kaunakakai": "MKK",
    "Kamuela": "MUE",
    "Kaneohe": "NGF",
    "Honolulu": "HNL",
    "Lanai City": "LNY",
    "Kahului": "OGG",
    "Camp Pohakuloa": "BSF",
    "Hilo": "ITO",
    "Hawi": "UPP",
    "Point Lay": "PIZ"
    };